repos:
  - repo: local
    hooks:
      - id: commit-msg-format
        name: Check commit message format
        entry: ./.pre-commit/check-commit-msg.sh
        language: system
        stages: [commit-msg]

      - id: changelog-update
        name: Generate CHANGELOG
        entry: ./.pre-commit/generate-changelog.sh
        language: system
        stages: [commit]
