[tool.semantic_release]
version_variable = "src/arthur_engine/__init__.py:__version__"
version_source = "commit"
branch = "main"
upload_to_pypi = false
upload_to_release = false
commit_parser = "conventional"
changelog_file = "CHANGELOG.md"

[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
/(
    \.venv
  | \.conda
  | \.git
  | __pycache__
  | build
  | dist
  | \.mypy_cache
)/
'''

[tool.ruff]
line-length = 88
target-version = "py311"
exclude = ["tests", ".conda"]
fix = true

# Match Black formatting
extend-select = ["I", "E", "F", "W", "UP"]
# "I" = isort compatibility
# "E", "W" = pycodestyle
# "F" = pyflakes
# "UP" = modern Python style updates

[tool.ruff.isort]
combine-as-imports = true
known-first-party = ["src"]
lines-after-imports = 2
force-sort-within-sections = true

[tool.pylint.master]
ignore = ["tests", ".venv", ".conda"]
extension-pkg-whitelist = ["pydantic"]

[tool.pylint.messages_control]
disable = [
    "missing-docstring",
    "invalid-name",
    "too-few-public-methods",
    "line-too-long",  # Let black handle this
    "trailing-whitespace",
]

[tool.pylint.format]
max-line-length = 88

[tool.pytest.ini_options]
asyncio_mode = "auto"
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
testpaths = ["tests"]
markers = [
    "asyncio: mark test as async"
]
