name: Lint and Test

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'release/*'
      - 'feature/*'

jobs:
  lint:
    name: 🧹 Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install project and lint tools
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort ruff pylint

      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Run Black (check only)
        run: black --check .

      - name: Run Ruff
        run: ruff check .

      - name: Run Pylint
        run: |
          pylint $(find . -name "*.py" -not -path "./venv/*")

  test:
    name: ✅ Pytest - All Tests Must Pass
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Tests (fail on any failure)
        run: pytest --exitfirst --strict-markers --tb=short
