name: Lint and Auto-Fix Python Code (Excludes tests)

on:
  pull_request:
    paths:
      - '**.py'
  push:
    paths:
      - '**.py'

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff pylint

      - name: Run formatters (black, isort, ruff)
        run: |
          black . --verbose --exclude '^test/'
          isort . --profile black --skip test
          ruff . --fix --exclude test

      - name: Run pylint (excluding test directory)
        run: |
          pylint $(git ls-files '*.py' | grep -v '^tests/')

      - name: Commit and push fixes
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-fix lint issues"
          git push
