name: Lint and Auto-Fix Python Code (Excludes tests)

on:
  push:
    branches-ignore:
      - main
      - develop
    paths:
      - '**.py'

  pull_request:
    branches-ignore:
      - main
      - develop
    paths:
      - '**.py'


jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'
      - name: Install project and lint tools
        run: |
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
            pip install black isort ruff pylint
              
      - name: Add src to PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff pylint

      - name: Run black (code formatter)
        run: |
          black . --verbose --exclude '^tests/'

      - name: Run isort (import sorter)
        run: |
          isort . --profile black --skip tests

      - name: Run ruff (linter + autofix)
        run: |
          ruff check . --fix --exclude tests

      - name: Run pylint (static analysis)
        run: |
          pylint $(git ls-files '*.py' | grep -v '^tests/')

      - name: Commit and push fixes
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "Arthur Linter"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-fix lint issues 🤖"
          git push
