name: Lint and Auto-Fix Python Code (Excludes tests)

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:  # Manual trigger from Actions tab

jobs:
  lint-and-fix:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort ruff pylint

      - name: Run black (code formatter)
        run: |
          black . --verbose --exclude '^test/'

      - name: Run isort (import sorter)
        run: |
          isort . --profile black --skip test

      - name: Run ruff (linter + autofix)
        run: |
          ruff check . --fix --exclude test

      - name: Run pylint (static analysis)
        run: |
          pylint $(git ls-files '*.py' | grep -v '^test/')

      - name: Commit and push fixes
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "chore: auto-fix lint issues 🤖"
          git push
