name: Ready for Release

on:
  pull_request:
    types: [labeled]

jobs:
  changelog:
    if: |
      github.event.label.name == 'ready-for-release' &&
      github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release build

      - name: Generate changelog
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python -m semantic_release changelog

      - name: Commit changelog to PR branch (if changed)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add CHANGELOG.md
          git diff --cached --quiet && echo "No changes to commit" && exit 0

          git commit -m "docs(changelog): update CHANGELOG.md"
          git push origin HEAD:${{ github.head_ref }}
